### ISSUE TITLE
error and questions

### ISSUE THREAD

**Issue by davephillips** [WIZARDISHUNGRY/vcvrack-rtlsdr#15]
Hi Jon ! I got my USB dongle set up and 'rtl_test -t' returns what it should. However, when I load your module I receive a series of messages with this error:

Reading error; count was 0

The Gqrx radio application isn't working either, so I think I've still a step or two to take before I'm there. Any suggestions what I might have missed ? I installed the rtl_sdr stuff from the Fedora 23 repos, perhaps I should build and install from source instead ?

**Comment by davephillips** [comment]
Hey Jon, ignore previous post. I reported my issue on the forum at rtl-sdr.com, got a reply this morning that led me to the solution. My mobo's USB port is underpowered for the dongle, so I attached the dongle to a powered hub and I now have a working system. Including your module, btw. :) I set up one of your examples you posted on Facebook, it works here just like your video. What fun ! I look forward to the module's development, please advise if there's anything you need tested, I'll be happy to help.

**Comment by wizardishungry** [comment]
Thanks! There's a lot of work to be done!
