### ISSUE TITLE
How fast should the tuning knob move?

### ISSUE THREAD

**Issue by wizardishungry** [WIZARDISHUNGRY/vcvrack-rtlsdr#36]
@davephillips, @dizzisound: want to take a look at this and chime in on the feel of the knob?

**Comment by davephillips** [comment]
The ballistics are better, I like it. :) Only had time for a single quick test, but the module appears and sounds operational now.

**Comment by dizzisound** [comment]
It looks appropriate to me too. Moving more slowly and smoothly, and improved usability when one tries out tuning.
